// <auto-generated by="the Blazor I18n Text compiler" />
namespace FormComponents.I18nText
{
    public partial class BlazorDemo : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Browser State Demo"</summary>
        public string BrowserStateDemo;
    }
}
