// <auto-generated by="the Blazor I18n Text compiler" />
namespace Toolbelt.I18nText
{
    public partial class MyResources : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextTableHash
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextTableHash.Hash => "o2tvz62kin";

        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Hello World!"</summary>
        public string Greeting;

        /// <summary>"Hello World!"</summary>
        public string Hello_World;
    }
}
